config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: "registrations" }
  root to: 'pages#home'
  get 'about', to: 'pages#about'
  resources :communities, only: [:index, :create] do
    collection do
      get :search
    end
  end

  resources :profiles, only: [:new, :create, :show, :update]
  resources :cards, except: [:new, :destroy] do
    member do
      get :archive
    end
    resources :comments, only: :create
    resources :card_recipients, only: :create
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <!-- COPY FROM DRESS UP -->
</div>

app/views/shared/_navbar-loggedin.html.erb
<!-- A vertical navbar -->
<!-- <nav class="list-group"> -->
<nav class="navbar sticky-top navbar-expand-sm navbar-light navbar-lewagon navbar-vertical">
  <ul class="nav flex-column nav-vertical">

      <!-- <li class="nav-item"> -->
        <%= link_to root_path do %>
          <h1 id= "nav-logo-short">n</h1>
        <% end %>
      <!-- </li> -->

      <!-- BOARD LINKS -->
      <div class="navbar-icons">

      <!-- missed -->
      <li class="nav-item">
        <% if cards_path(query: "missed") %>
          <% if current_page?(cards_path(query: "missed")) %>
            <div class="board-icon-purple">
              <div class="active-side-indicator">
                <!-- Nothing here -->
              </div>
              <div class="icon-box">
                <div class="noti-badge no-noti"></div>
                <%= link_to cards_path(query: "missed") do %>
                  <%= image_tag "ic-board_missed-white.svg", class: "nav-icon" %>
                <% end %>
              </div>
            </div>
          <% else %>
            <div class="board-icon">
              <div class="icon-box">
                <div class="noti-badge no-noti"></div>
                <%= link_to cards_path(query: "missed") do %>
                  <%= image_tag "ic-board_missed.svg", class: "nav-icon" %>
                <% end %>
              </div>
            </div>
          <% end %>
        <% end %>
      </li>

      <!-- parcels -->
      <li class="nav-item">
        <% if current_page?(cards_path(query: "parcels")) %>
          <div class="board-icon-purple">
            <div class="active-side-indicator">
              <!-- Nothing here -->
            </div>
            <div class="icon-box">
              <div class="noti-badge no-noti"></div>
              <%= link_to cards_path(query: "parcels") do %>
                <%= image_tag "ic-board_parcels-white.svg", class: "nav-icon" %>
              <% end %>
            </div>
          </div>
        <% else %>
          <div class="board-icon">
            <div class="icon-box">
              <div class="noti-badge no-noti"></div>
              <%= link_to cards_path(query: "parcels") do %>
                <%= image_tag "ic-board_parcels.svg", class: "nav-icon" %>
              <% end %>
            </div>
          </div>
        <% end %>
      </li>

      <!-- mutual help -->
      <li class="nav-item">
        <% if current_page?(cards_path(query: "mutual_help")) %>
          <div class="board-icon-purple">
            <div class="active-side-indicator">
              <!-- Nothing here -->
            </div>
            <div class="icon-box">
              <div class="noti-badge no-noti"></div>
              <%= link_to cards_path(query: "mutual_help") do %>
                <%= image_tag "ic-board_mutual-help-white.svg", class: "nav-icon" %>
              <% end %>
            </div>
          </div>
        <% else %>
          <div class="board-icon">
            <div class="icon-box">
              <div class="noti-badge no-noti"></div>
              <%= link_to cards_path(query: "mutual_help") do %>
                <%= image_tag "ic-board_mutual-help.svg", class: "nav-icon" %>
              <% end %>
            </div>
          </div>
        <% end %>
      </li>

      <!-- community -->
      <li class="nav-item">
        <% if current_page?(cards_path(query: "community")) %>
          <div class="board-icon-purple">
            <div class="active-side-indicator">
              <!-- Nothing here -->
            </div>
            <div class="icon-box">
              <div class="noti-badge no-noti"></div>
              <%= link_to cards_path(query: "community") do %>
                <%= image_tag "ic-board_community-white.svg", class: "nav-icon" %>
              <% end %>
            </div>
          </div>
        <% else %>
          <div class="board-icon">
            <div class="icon-box">
              <div class="noti-badge no-noti"></div>
              <%= link_to cards_path(query: "community") do %>
                <%= image_tag "ic-board_community.svg", class: "nav-icon" %>
              <% end %>
            </div>
          </div>
        <% end %>
      </li>
    </div>
  </ul>
  <ul>

    <li class="nav-item">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </li>

    <li class="nav-item">

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <% if user_signed_in? %>

            <li class="nav-item dropup">
              <!-- FOR DEFAULT AVATAR -->
              <% if current_user.profile.avatar.attached? %>
                <%= image_tag current_user.profile.avatar, class: "avatar-big dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <% else  %>
                <%= navbar_avatar_for(current_user.profile) %>
              <% end %>

              <div class="dropdown-menu dropright" aria-labelledby="navbarDropdown">

                 <div class="dropdown-group">
                  <%= image_tag "ic-mycards.svg", class: "nav-dropdown-icon" %>
                  <%= link_to "My cards", cards_path(query: "my-cards"), class: "drop-item" %>
                </div>

                <div class="dropdown-group">
                  <%= image_tag "ic-profile.svg", class: "nav-dropdown-icon" %>
                  <% if current_user.profile %>
                    <%= link_to "My profile", profile_path(current_user.profile), class: "drop-item" %>
                  <% end %>
                </div>

                <div class="dropdown-group">
                  <%= image_tag "ic-settings.svg", class: "nav-dropdown-icon" %>
                  <%= link_to "Settings", "#", class: "drop-item" %>
                </div>

                <div class="dropdown-group">
                  <%= image_tag "ic-logout.svg", class: "nav-dropdown-icon" %>
                  <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "drop-item" %>
                </div>

              </div>

            </li>

          <% else %>
            <li class="nav-item">
              <%= link_to "Login", new_user_session_path, class: "nav-link" %>
            </li>
          <% end %>
        </ul>
      </div>
    </li>
  </ul>
</nav>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-lewagon navbar-horizontal nav-transparent fixed <%= 'navbar-margin-top' if controller_name == 'registrations' || controller_name == 'sessions' %>" id="nav">

  <!-- HOME link via 'neighbors' if logged out to home, if logged-in, to dashboard -->
  <%= link_to user_signed_in? ? cards_path(query: "missed") : root_path, class: "navbar-brand" do %>
   <h1 class="nav-logo-long <%= 'nav-logo-grey' if controller_name == 'registrations' || controller_name == 'sessions' || controller_name == 'communities' || current_page?(about_path) %>">neighbors.</h1>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
     <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <li class="nav-item d-flex" >
        <% if !user_signed_in? %>
          <% if current_page?(root_path) %>
            <%= link_to "Log In", new_user_session_path, class: "btn btn-secondary-white btn-medium btn-login" %>
            <%= link_to "Sign Up", search_communities_path, class: "btn btn-primary btn-medium" %>
          <% elsif current_page?(about_path) %>
            <%= link_to "Log In", new_user_session_path, class: "btn btn-secondary btn-medium btn-login" %>
            <%= link_to "Sign Up", search_communities_path, class: "btn btn-primary btn-medium" %>
          <% elsif current_page?(communities_path) || current_page?(search_communities_path) || current_page?(new_profile_path) || current_page?(new_user_registration_path) %>
            <div class="nav-log">
            <p class="description-card">Got an account?</p>
            <%= link_to "Log In", new_user_session_path, class: "btn btn-secondary btn-medium btn-login" %>
          </div>
          <% else %>
            <div class="nav-log">
              <p class="description-card">No account, yet?</p>
              <%= link_to "Sign Up", search_communities_path, class: "btn btn-secondary btn-medium" %>
            </div>
          <% end %>
        <% else %>
          <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "btn btn-primary btn-medium"%>
        <% end %>
      </li>
    </ul>
  </div>
</div>