config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: "registrations" }
  root to: 'pages#home'
  get 'about', to: 'pages#about'
  resources :communities, only: [:index, :create] do
    collection do
      get :search
    end
  end

  resources :profiles, only: [:new, :create, :show, :update]
  resources :cards, except: [:new, :destroy] do
    member do
      get :archive
    end
    resources :comments, only: :create
    resources :card_recipients, only: :create
  end
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
  has_many :card_recipients
  has_many :users, through: :card_recipients
  has_many :comments
  has_many_attached :pictures
  accepts_nested_attributes_for :card_recipients

  validates :board, :category, :title, :users, presence: true
  validates :board, inclusion: { in: ['parcels', 'mutual_help', 'community'] }
  validates :category, inclusion: { in: ['action', 'request', 'info', 'offer', 'question'] }

  CARD_BOARDS = ['parcels', 'mutual_help', 'community']
  CARD_CATEGORIES = ['action', 'request', 'info', 'offer', 'question']
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:show, :edit, :archive, :update]

  def index
    # View parcels board
    if params[:query] == "parcels"
      @cards = policy_scope(Card).where(board: "parcels").where(archived: false).order(created_at: :desc)
      @title = "Parcels"

    # View mutual help board
    elsif params[:query] == "mutual_help"
      @cards = policy_scope(Card).where(board: "mutual_help").where(archived: false).order(created_at: :desc)
      @title = "Mutual help"

    # View community board
    elsif params[:query] == "community"
      @cards = policy_scope(Card).where(board: "community").where(archived: false).order(created_at: :desc)
      @title = "Community"

    # View missed board
    elsif params[:query] == "missed"
      missed_cards = policy_scope(Card).where("created_at > ?", current_user.last_logout)
      missed_comments = policy_scope(Card).joins(:comments).where("comments.created_at > ?", current_user.last_logout)
      @cards = missed_cards.union(missed_comments).order(created_at: :desc)
      @title = "What you've missed"

    # View my cards page
    elsif params[:query] == "my-cards"
      @cards = policy_scope(Card).where(archived: false).where(user: current_user).order(created_at: :desc)
      @title = "My cards"

    # View
    elsif params[:query] == "my-cards-archived"
      @cards = policy_scope(Card).where(user: current_user, archived: true).order(created_at: :desc)
      @title = "My cards"

    else
      missed_cards = policy_scope(Card).where("created_at > ?", current_user.last_logout)
      missed_comments = policy_scope(Card).joins(:comments).where("comments.created_at > ?", current_user.last_logout)
      @cards = missed_cards.union(missed_comments).order(created_at: :desc)
      @title = "What you've missed"

    end
    @empty_card = Card.new
    @empty_recipient = CardRecipient.new
    @empty_comment = Comment.new
  end

  def show
    @user = current_user
    authorize @card
  end

  def create
    @card = Card.new(card_params)
    @user = current_user
    @card.user = @user
    @card_users = User.where(id: params['card'][:user_ids])
    @card_users.each do |user|
      CardRecipient.create(user: user, card: @card)
    end
    authorize @card
    @card.save!
    if @card.board == "parcels"
      redirect_to cards_path(query: "parcels")
    elsif @card.board == "mutual_help"
      redirect_to cards_path(query: "mutual_help")
    elsif cards_path(query: "community")
      redirect_to cards_path(query: "community")
    end
  end

  def edit
    @user = current_user
    authorize @card
  end

  def update
    @card.update(card_params)
    authorize @card
    redirect_to cards_path(query: "my-cards")
  end

  def archive
    @card.archived = true
    @card.save
    redirect_to cards_path(query: "my-cards-archived")
    authorize @card
  end

  private

  def set_card
    @card = Card.find(params[:id])
  end

  def card_params
    params.require(:card).permit(:board, :category, :title, :description, :start_date, :start_time, :end_date, :end_time, :archived, pictures: [] )
  end
end

app/views/cards/_form.html.erb
<div id="new-card" class="modal fade" role="dialog">
  <div class="modal-dialog modal-lg modal-dialog-centered">
    <div class="modal-content card-modal">
    <!-- PARTIAL FOR CARD EDIT -->
          <div class="modal-body overflow-auto form-background">
            <%= simple_form_for card  do |f| %>
              <h1 class="headline">Add a card</h1>
                <%= f.input :board,
                  collection: [['Parcels 📦', Card::CARD_BOARDS[0]], ['Mutual Help 🤝', Card::CARD_BOARDS[1]], ['Community 🏠', Card::CARD_BOARDS[2]]],
                  label: "Select a board" %>
                <div class="input-box">
                  <%= f.input :category,
                    label: "Select a category",
                    collection: Card::CARD_CATEGORIES,
                    as: :radio_buttons,
                    input_html: { class: "input-category" },
                    item_wrapper_class: 'category-item' %>
                </div>
                <%= f.association :users,
                  collection: User.where(community_id: current_user.community_id).where.not(id: current_user.id).order(:last_name),
                  as: :check_boxes,
                  multiple: true,
                  include_hidden: false,
                  label_method: :last_name,
                  label: "Who is this card for?",
                  input_html: { class: "input-users" } %>
                <div id="input-dates">
                  <%= f.input :start_date,
                    as: :string,
                    required:false,
                    input_html: {class: "datepicker start_date"} %>
                  <%= f.input :end_date,
                    as: :string,
                    required: false,
                    input_html: {class: "datepicker end_date"} %>
                </div>
                <div id="input-times">
                  <%= f.input :start_time, input_html: {class: "start_time"} %>
                  <%= f.input :end_time, input_html: {class: "end_time"} %>
                </div>
                <%= f.input :title %>
                <%= f.input :description %>
                <%= f.input :pictures, as: :file, input_html: {multiple: true} %>
              <!-- </div> -->

              <div class="form-actions">
                <%= f.submit "Save Card", class: "btn btn-primary btn-shadow"%>
              </div>
            <% end %>
      </div>
    </div>
  </div>
</div>

app/views/cards/_show.html.erb
<div id="myModal<%= card.id %>" class="modal fade" role="dialog">
  <div class="modal-dialog modal-lg modal-dialog-centered">

    <!-- Modal content-->
    <div class="modal-content card-modal">
      <div class="modal-left">
        <div class="card-content-show">
          <div class="card-upper-content">
            <div class="card-top">

              <!-- Card Menu (archive/edit) -->
              <% if current_user == card.user && card.archived == false %>
                <div class='<%= "toggle-id-#{card.id} card-actions display-menu" %>'>
                  <div class="link-wrapper">
                    <div class="hover-link edit">
                      <%= link_to edit_card_path(card), class: "actual-link" do %>
                        <%= image_tag "ic-edit.svg", class: "icon-hover-menu" %>
                        <p class="hover-menu-text">Edit</p>
                      <% end %>
                    </div>
                    <div class="hover-link archive">
                      <%= link_to archive_card_path(card), class: "actual-link" do %>
                        <%= image_tag "ic-archive.svg", class: "icon-hover-menu" %>
                        <p class="hover-menu-text">Archive</p>
                      <% end %>
                    </div>
                  </div>
                </div>
              <% end %>

              <p class="category <%= card.category %>"><%= card.category %></p>
              <div class="time-menu">
                <p class="date-time">
                  <% if card.created_at.strftime("%e %m %y") == Date.today.strftime("%e %m %y")%>
                     Today, <%= card.created_at.strftime("%l:%M %p") %>
                  <% elsif card.created_at.strftime("%e %m %y") == Date.yesterday.strftime("%e %m %y") %>
                    Yesterday, <%= card.created_at.strftime("%l:%M %p") %>
                  <%# elsif (card.created_at.strftime("%e %m %y") > Date.today.strftime("%e %m %y") - 7) && (card.created_at.strftime("%e %m %y") < Date.yesterday.strftime("%e %m %y")) %>
                    <%#= card.created_at.strftime("%A, %l:%M %p") %>
                  <% else %>
                    <%= card.created_at.strftime("%B %d, %l:%M %p") %>
                  <% end %>
                </p>
                <% if current_user == card.user && card.archived == false %>
                  <%= image_tag "ic-menu.svg", class: "icon-menu", data: { card_id: card.id }, id: "menu-icon" %>
                <% end %>
              </div>
            </div>
            <div class="card-middle">
              <p class="from-who"><%= card.user.first_name %> <%= card.user.last_name %>, <%= card.user.profile.floor %></p>
              <p class="title"><%= card.title %></p>
            </div>
            <div class="card-lower-content-show">
              <p class="date-time">
                    <% if card.start_date.present? || card.end_date.present? || card.start_time.present? || card.end_time.present? %>
                        When:
                    <% if card.start_date.present? %>
                      <%= card.start_date.strip %>
                    <% end %>
                    <% if card.end_date.present? %>
                      - <%= card.end_date.strip %>
                    <% end %>
                    <% if card.start_time.present? %>
                      <% if card.start_date %>
                      <% end %><%= ", " + card.start_time %>
                    <% end %>
                    <% if card.end_time.present? %>
                      - <%= card.end_time %>
                    <% end %>
                  <% end %>
              </p>
            <p class="card-description description-card"><%= card.description %></p>

             <div class="card-pictures uploaded-pic">
                <% card.pictures.each do |picture| %>
                  <%= image_tag picture, class: "card-photos" %>
                <% end %>
            </div>
          </div>
        </div>

          <div class="card-avatars padding-avatar-sm-top">
            <% card.users.order(:last_name).each do |recipient| %>
              <div class="pairs">
                <% if recipient.profile.avatar.attached? %>
                   <%= image_tag recipient.profile.avatar, class: "avatar-small" %>
                <% else  %>
                  <%= chat_avatar_for(recipient.profile) %>
                <% end %>
                <div class="hidden-name"><%= recipient.first_name %> <%= recipient.last_name %></div>
              </div>
            <% end %>

          </div>
        </div>
      </div>
      <!-- HERE STARTS COMMENT SECTION -->
      <%= render "comments/chat", card: card, empty_comment: empty_comment %>
    </div>

  </div>
</div>

app/views/cards/edit.html.erb
<div id="new-card">
  <div class="modal-dialog modal-lg modal-dialog-centered">
    <div class="modal-content card-modal">

          <div class="modal-body overflow-auto form-background">
            <%= simple_form_for @card  do |f| %>
              <h1 class="headline">Add a card</h1>
                <%= f.input :board,
                  collection: [['Parcels 📦', Card::CARD_BOARDS[0]], ['Mutual Help 🤝', Card::CARD_BOARDS[1]], ['Community 🏠', Card::CARD_BOARDS[2]]],
                  label: "Select a board" %>
                <div class="input-box">
                  <%= f.input :category,
                    label: "Select a category",
                    collection: Card::CARD_CATEGORIES,
                    as: :radio_buttons,
                    input_html: { class: "input-category" },
                    item_wrapper_class: 'category-item' %>
                </div>
                <%= f.association :users,
                  collection: User.all,
                  as: :check_boxes,
                  multiple: true,
                  include_hidden: false,
                  label_method: :last_name,
                  label: "Who is this card for?",
                  input_html: { class: "input-users" } %>
                <div id="input-dates">
                  <%= f.input :start_date,
                    as: :string, required:
                    false, input_html: {class: "datepicker start_date"} %>
                  <%= f.input :end_date,
                    as: :string, required:
                    false,
                    input_html: {class: "datepicker end_date"} %>
                </div>
                <div id="input-times">
                  <%= f.input :start_time, input_html: {class: "start_time"} %>
                  <%= f.input :end_time, input_html: {class: "end_time"} %>
                </div>
                <%= f.input :title %>
                <%= f.input :description %>
                <%= f.input :pictures, as: :file, multiple: true %>
              <div class="form-actions">
                <%= f.submit "Save Card", class: "btn btn-primary btn-shadow"%>
              </div>
            <% end %>
      </div>
    </div>
  </div>
</div>

app/views/cards/index.html.erb
<div class="container-dashboard">
  <div class="top">
    <div class="dashboard-headings">
      <p>Welcome back, <%= current_user.first_name.capitalize %></p>
      <h1><%= @title %></h1>
    </div>
    <div class="my-cards-tabs">
      <!-- if view is my-cards -->
      <% if current_page?(cards_path(query: "my-cards")) %>
      <div class="primary-link"><%= link_to "Show all", cards_path(query: "my-cards") %></div>
      <div class="secondary-link"><%= link_to "Show archived", cards_path(query: "my-cards-archived") %></div>
      <!-- if view is my-cards-archived -->
      <% elsif current_page?(cards_path(query: "my-cards-archived")) %>
      <div class="secondary-link"><%= link_to "Show all", cards_path(query: "my-cards") %></div>
      <div class="primary-link"><%= link_to "Show archived", cards_path(query: "my-cards-archived") %></div>
      <% end %>
    </div>
    <!-- Neighbors Avatars upper right corner -->
    <div id="neighbors">
      <% current_user.community.users.each do |user| %>
        <% if user.profile.avatar.attached? %>
          <%= image_tag user.profile.avatar, class: "avatar-big avatar-margin" %>
        <% else  %>
          <%= index_avatar_for(user.profile) %>
        <% end %>
      <% end %>
    </div>
    <!-- Neighbors index on click on avatars upper right corner -->
    <div id="neighbors-index" class="display-none">
      <div class="neighbors-top">
        <div>
          <p class="title">Your community</p>
          <p class="from-who"><%= pluralize(current_user.community.users.count, "member") %></p>
        </div>
        <%= image_tag "ic-close.svg", id: "ic-close" %>
      </div>
      <% current_user.community.users.order(:last_name).each do |user| %>
        <%= link_to profile_path(user.profile), class:"neighbor" do %>
          <% if user.profile.avatar.attached? %>
            <%= image_tag user.profile.avatar, class: "avatar-small-list" %>
          <% else %>
            <%= list_avatar_for(user.profile) %>
          <% end %>
          <p class="description-card"><%= user.first_name %> <%= user.last_name %>, <%= user.profile.floor %></p>
        <% end %>
      <% end %>
    </div>

    <button type="button" class="btn-plus btn-shadow add" data-toggle="modal" data-target="#new-card"><%= image_tag "ic_plus-big.svg" %></button>
  </div>

  <!-- DISPLAY CARDS -->
  <% if @cards.length > 0 %>
    <div class="cards cards-on-index">
      <% @cards.each do |card| %>
      <!-- MODAL LINK STARTS HERE -->
        <button type="button" id="button-card-<%= card.id %>" class="btn btn-light btn-lg" data-toggle="modal" data-target="#myModal<%= card.id %>">
          <!-- CARD CONTENT STARTS HERE -->
          <div class="custom-card">
            <div class="card-content">
              <div class="card-upper-content">
                <div class="card-top">
                  <p class="category <%= card.category %>"><%= card.category %></p>
                  <div class="time-menu">
                    <p class="date-time">
                      <% if card.created_at.strftime("%e %m %y") == Date.today.strftime("%e %m %y")%>
                        Today, <%= card.created_at.strftime("%l:%M %p") %>
                      <% elsif card.created_at.strftime("%e %m %y") == Date.yesterday.strftime("%e %m %y") %>
                        Yesterday, <%= card.created_at.strftime("%l:%M %p") %>
                      <%# elsif (card.created_at.strftime("%e %m %y") > Date.today.strftime("%e %m %y") - 7) && (card.created_at.strftime("%e %m %y") < Date.yesterday.strftime("%e %m %y")) %>
                        <%#= card.created_at.strftime("%A, %l:%M %p") %>
                      <% else %>
                        <%= card.created_at.strftime("%B %d, %l:%M %p") %>
                      <% end %>
                    </p>
                  </div>
                </div>
                <div class="card-middle">
                  <p class="from-who"><%= card.user.first_name %> <%= card.user.last_name %>, <%= card.user.profile.floor %></p>
                  <p class="title"><%= card.title %></p>
                </div>
                <p class="date-time">
                  <% if card.start_date.present? || card.end_date.present? || card.start_time.present? || card.end_time.present? %>
                        When:
                    <% if card.start_date.present? %>
                      <%= card.start_date.strip %>
                    <% end %>
                    <% if card.end_date.present? %>
                      - <%= card.end_date.strip %>
                    <% end %>
                    <% if card.start_time.present? %>
                      <% if card.start_date %>
                      <% end %><%= ", " + card.start_time %>
                    <% end %>
                    <% if card.end_time.present? %>
                      - <%= card.end_time %>
                    <% end %>
                  <% end %>
                </p>
                <p class="card-description description-card"><%= truncate(card.description,  :length => 82) %></p>
              </div>
              <div class="card-lower-content">
                <div class="card-avatars">
                  <% card.users.order(:last_name).each do |recipient| %>
                    <!-- <div class="card-index-avatars"> -->
                      <div class="pairs">
                        <% if recipient.profile.avatar.attached? %>
                          <%= image_tag recipient.profile.avatar, class: "avatar-small" %>
                        <% else  %>
                          <%= chat_avatar_for(recipient.profile) %>
                        <% end %>
                        <div class="hidden-name"><%= recipient.first_name %> <%= recipient.last_name %></div>
                      </div>
                    <!-- </div> -->
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </button>
        <!-- RENDERING SHOW -->
        <%= render 'show', :card => card, empty_comment: @empty_comment %>
      <% end %>
    </div>
  <% else %>
    <div class="empty-cards-center">
      <div class="center">
        <%= cl_image_tag "https://res.cloudinary.com/divi2012/image/upload/v1615219455/illu-dashboard_empty-state_qescle.svg", class: "empty-state" %>
        <p class="title">Nothing to see here, yet! Add a card now</p>
      </div>
    </div>
  <% end %>
</div>


<!-- RENDERING NEW -->

<%= render "form", card: @empty_card %>